name:                TippyGods
version:             0.1.0.0
github:              Nolrai/TippyGods
license:             BSD3
author:              Christina Upshaw
maintainer:          chrisaupshaw@gmail.com
copyright:           2023 Christina Upshaw

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Nolrai/TippyGods#readme>

dependencies:
- base >= 4.11 && < 5
- rio >= 0.1.12.0 && < 0.2
- cassava >= 0.5 && < 0.6
- diagrams ^>= 1.4
- diagrams-postscript ^>= 1.5
- diagrams-svg ^>= 1.4
- diagrams-lib ^>= 1.4
- SVGFonts ^>= 1.8
- lens >= 5.1 && < 6
- template-haskell >= 2.18 && < 3
- bytestring >= 0.11 && < 1
- directory >= 1.3 && < 2
- text ^>= 1.2.5 

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  TippyGods-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - TippyGods
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  TippyGods-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - TippyGods
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
